#!/usr/bin/env node
/* eslint-disable no-console */

const { execSync } = require('child_process');

function run(cmd) {
  try {
    execSync(cmd, { stdio: 'inherit' });
  } catch (err) {
    console.error(`pre-commit: comando falhou: ${cmd}`);
    process.exit(err.status || 1);
  }
}

console.log('pre-commit: rodando docs:check');
run('npm run docs:check');
